### ISSUE TITLE
BlockStream peer timeouts

### ISSUE THREAD

**Issue by mappum** [mappum/bitcoin-net#10]
It seems that very many peers are timing out when responding with `blocks` messages when we request many of them via `BlockStream`. I'm not sure if we're hitting some Bitcoin Core rate limiting, or if a bug is preventing us from seeing the response.

**Comment by fanatid** [comment]
@mappum interesting, can you paste code for repeating?

**Comment by mappum** [comment]
@fanatid You can run the tests with `DEBUG=bitcoin-net:peergroup,bitcoin-net:peer npm test` and see the debug output once it gets to the `createBlockStream` test.

**Comment by mappum** [comment]
It appears that the timeouts were being caused by issues with the decoder pipeline, so some received packets were being dropped. The issue is fixed in 77294e69bec5c4ece3d19c8e4a619b498252abf0. Now `BlockStream` and `BlockHeader` runs much faster since we don't have to keep disconnecting/connecting peers.
