### ISSUE TITLE
A convenient way to persist a transaction stream?

### ISSUE THREAD

**Issue by paulkernfeld** [mappum/bitcoin-net#35]
I'm interested in caching the results of a particular transaction stream. This will let me read the transactions off disk, and then start looking at new transactions at the point where my disk cache stops. I'm currently doing this in a pretty simple way, by just caching each transaction that comes out of the transaction stream. What I'd like to do is to also cache that a particular block _doesn't contain any matching transactions._ Right now this seems a little tricky because the transaction stream doesn't tell us when it sees a block without transactions. I can think of a few ways to do this, but do you have any recommendations for the "right" way to approach this?

One thing I was thinking about is that the transaction stream could have an option where it can output an object indicating that it has finished looking at a particular block. This may be a bit too closely tailored to my use case, though.

Another idea is to have a stream that reads from both the block stream and the transaction stream and kind of zips their outputs together into a single stream. This might be a little bit more work but it could be better-factored.

**Comment by mappum** [comment]
TransactionStreams are actually just a pretty simple transform for
BlockStream, where the transactions are output for each block. Each
TransactionStream has a `blocks` property which is a reference to the
underlying BlockStream, so you could do something like
`transactionStream.blocks.on('data', (block) => console.log(block.height))`.

**Comment by paulkernfeld** [comment]
Thanks for the quick reply!

I think it's a little bit trickier than that, because the block stream will emit that `data` event before the block has been completely processed by the transaction stream, right? So, you're persisting that block before guaranteeing that you've checked the block for transactions. Ideally, you should check the block for transactions, _then_ persist the block. However, now that I'm writing this I'm thinking that perhaps it's worth it to accept this small race condition for now and fix it later.

**Comment by paulkernfeld** [comment]
Actually, now that I'm trying this, it looks like the blocks stream is getting pretty far ahead of the transaction stream (like 500 blocks ahead). Does that sound possible, or is that a sign that I'm doing something wrong?

**Comment by mappum** [comment]
Hm, you might be better off creating a `BlockStream` instead of `TransactionStream`, and just iterate through the `block.transactions` array. That's simpler and then it's not possible for the blocks to get ahead of the transactions.

Something could definitely be wrong with my code that is causing that problem, those streams are mostly untested (but I'm going to move them into their own module this week since `bitcoin-net` has gotten pretty big).

**Comment by paulkernfeld** [comment]
All right, I implemented your suggestion and it works great.

I wasn't thinking that there was actually a problem in your code. Maybe the data are being buffered somewhere? I don't know how that works.
