### ISSUE TITLE
Only connects to self

### ISSUE THREAD

**Issue by Head** [mappum/bitcoin-net#42]
When I run the sample I'm getting flooded with

> connected to peer 192.168.1.140

Does this even work anymore?

**Comment by mappum** [comment]
I fixed the example to not spam connections anymore, but I'm not sure why your client is only connecting to that local address. Are you using any unconventional network configurations?

Also, let me know what output you get when you run `dig seed.bitcoin.sipa.be`.

**Comment by Head** [comment]
Ah ok, peer.socket._sockname.address was just the wrong IP :)
thx for fixing the example. looks good now.
