### ISSUE TITLE
Flood of peer connections 

### ISSUE THREAD

**Issue by Head** [mappum/bitcoin-net#49]
The browser debug is flooding (and crashing the browser) with

> bitcoin-net:peergroup discovery connection error: Peer does not have any peers to exchange

**Comment by mappum** [comment]
I'm planning on refactoring a lot of the `peer-exchange` web seed stuff this week, which is where these errors are coming from. So this will be fixed very soon (and this module should be much more reliable in the browser).

**Comment by Head** [comment]
Any news/branch I can test?

**Comment by mappum** [comment]
I'll deploy the changes today (it also involves changes to other repos such as `peer-exchange`).
