### ISSUE TITLE
bitcoinjs-lib TransactionBuilder can't work with BN

### ISSUE THREAD

**Issue by Head** [mappum/bitcoin-net#64]
`inv.on('tx', (tx) => {bitcoinjs.TransactionBuilder.fromTransaction(tx)}` is failing on the outs.value in tx with:
Expected UInt53, got BN

**Comment by mappum** [comment]
We could make this module output transactions with a UInt53 output value to support bitcoinjs. Although this can break with currencies that use larger currency amounts (e.g. dogecoin). Not sure the right way to handle this yet.

For now, you could just convert manually:

``` js
for (let output of tx.outs) {
  output.value = output.value.toNumber()
}
```

**Comment by Head** [comment]
Works, thanks. But it don't fix my address decoding problems. And also not that I receive transactions I don't want to get... (and run into a timeout later). But that's maybe another problem...
